PROJECT IS OUTDATED, THE ORIGINAL OWNER OF THE REPO HASNT UPDATED IT SINCE JULY 2025 

I "BUBBLESTHEDEV" IS UPDATING THE REPO AND MAKING IT BETTER 
MAKING SURE ALL DEPENDENCY ARE UPDATED AND CODE IS UPDATED.
